"""Generate the SYNTHETIC sample data set under data/ (deterministic, seeded).

The series are geometric random walks with a few engineered bars so that the
fixture demo on 2026-09-12 produces a known set of candidate signals:

  AAPL  +6.2% close and 3.2x volume on the last session
  NVDA  new 52-week high; position P&L crosses +20%; >40% concentration
  AMD   earnings in 4 days      MSFT  earnings in 5 days

Run from the repository root:  python3 scripts/make_sample_data.py
"""
from __future__ import annotations

import math
import random
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from digest.config import load_config  # noqa: E402
from digest.signals import evaluate  # noqa: E402
from digest.sources import FixtureSource  # noqa: E402

SEED = 20260912
END = date(2026, 9, 12)  # a Saturday: equities end on Fri 2026-09-11, crypto on Sat
SESSIONS = 300
ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

# ticker -> (final close, daily vol, base volume, trades on weekends)
SPECS = {
    "AAPL": (232.15, 0.014, 55_000_000, False),
    "NVDA": (120.48, 0.022, 250_000_000, False),
    "TSLA": (251.30, 0.030, 90_000_000, False),
    "MSFT": (415.20, 0.012, 22_000_000, False),
    "AMD": (158.75, 0.025, 45_000_000, False),
    "BTC-USD": (61_234.50, 0.028, 32_000, True),
}
HEADER = "# SYNTHETIC DATA generated by scripts/make_sample_data.py (seed {seed}). Not real market prices.\n"


def sessions(end: date, n: int, weekends: bool) -> list[date]:
    out, d = [], end
    while len(out) < n:
        if weekends or d.weekday() < 5:
            out.append(d)
        d -= timedelta(days=1)
    return out[::-1]


def walk(rng: random.Random, n: int, vol: float) -> list[float]:
    closes, level = [], 100.0
    for _ in range(n):
        level *= math.exp(rng.gauss(0.0002, vol))
        closes.append(level)
    return closes


def keep_inside_range(closes: list[float]) -> None:
    """Make sure the final close is neither a 52-week high nor low (add a bump/dip)."""
    last = closes[-1]
    if max(closes[:-1]) < last * 1.03:
        for i in range(40, 80):
            closes[i] *= 1 + 0.12 * math.sin(math.pi * (i - 40) / 40)
        closes[60] = max(closes[60], last * 1.05)
    if min(closes[:-1]) > last * 0.97:
        for i in range(120, 160):
            closes[i] *= 1 - 0.12 * math.sin(math.pi * (i - 120) / 40)
        closes[140] = min(closes[140], last * 0.95)


def build(ticker: str, rng: random.Random) -> list[tuple[date, float, float, float, float, int]]:
    final, vol, base_vol, weekends = SPECS[ticker]
    dates = sessions(END, SESSIONS, weekends)
    closes = walk(rng, SESSIONS, vol)
    if ticker == "AAPL":
        closes[-1] = closes[-2] * 1.062                    # +6.2% daily move
        keep_inside_range(closes)
    elif ticker == "NVDA":
        scale = 116.5 / closes[-3]                           # normalise, then cap the prior range
        closes = [min(c * scale, 119.0) for c in closes[:-2]] + [118.0, 120.48]
    else:
        closes[-1] = closes[-2] * (1 + rng.uniform(-0.01, 0.01))  # quiet last session
        keep_inside_range(closes)
    scale = final / closes[-1]
    closes = [round(c * scale, 2) for c in closes]

    rows, volumes = [], []
    for i, (d, c) in enumerate(zip(dates, closes)):
        prev = closes[i - 1] if i else c
        o = round(prev * (1 + rng.gauss(0, 0.003)), 2)
        h = round(max(o, c) * (1 + abs(rng.gauss(0, 0.006))), 2)
        lo = round(min(o, c) * (1 - abs(rng.gauss(0, 0.006))), 2)
        v = int(base_vol * math.exp(rng.gauss(0, 0.30)))
        volumes.append(v)
        rows.append((d, o, h, lo, c, v))
    avg20 = sum(volumes[-21:-1]) / 20
    last_mult = 3.2 if ticker == "AAPL" else rng.uniform(0.8, 1.2)
    d, o, h, lo, c, _ = rows[-1]
    rows[-1] = (d, o, h, lo, c, int(avg20 * last_mult))
    return rows


def main() -> None:
    (DATA / "sample").mkdir(parents=True, exist_ok=True)
    for ticker in SPECS:
        rng = random.Random(f"{SEED}:{ticker}")
        lines = [HEADER.format(seed=SEED), "Date,Open,High,Low,Close,Volume\n"]
        lines += [f"{d},{o},{h},{lo},{c},{v}\n" for d, o, h, lo, c, v in build(ticker, rng)]
        (DATA / "sample" / f"{ticker}.csv").write_text("".join(lines))
    (DATA / "earnings_calendar.csv").write_text(
        "# SYNTHETIC earnings calendar for the sample data set; dates are fictional.\n"
        "ticker,date\nAMD,2026-09-16\nMSFT,2026-09-17\nTSLA,2026-10-21\nAAPL,2026-10-29\nNVDA,2026-11-18\n"
    )
    # Self-check: the engineered scenario must hold under the package's own rules.
    fired = sorted((s.ticker, s.rule) for s in evaluate(load_config(ROOT / "watchlist.yaml"), FixtureSource(DATA), END) if s.fired)
    expected = sorted([("AAPL", "daily_move"), ("AAPL", "volume_spike"), ("NVDA", "week52_high"),
                       ("NVDA", "pnl_cross"), ("NVDA", "concentration"), ("AMD", "earnings_soon"),
                       ("MSFT", "earnings_soon")])
    assert fired == expected, f"scenario drifted:\n got {fired}\n want {expected}"
    print(f"wrote {len(SPECS)} synthetic series + earnings calendar to {DATA}; scenario verified")


if __name__ == "__main__":
    main()
